name: CI

on:
  push:
  pull_request:
    types: [opened]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Runs code QA and tests
        run: docker run --rm -v "$(pwd):/app" -w /app -t node:lts-alpine sh -c 'yarn install --frozen-lockfile && yarn build'
